# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joeconfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.resize(580, 430)
        self.centralWidget = QtWidgets.QWidget(Configuration)
        self.centralWidget.setObjectName("centralWidget")
        self.mediaBox = QtWidgets.QGroupBox(self.centralWidget)
        self.mediaBox.setGeometry(QtCore.QRect(10, 10, 531, 151))
        self.mediaBox.setObjectName("mediaBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.mediaBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 40, 421, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.direcoryGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.direcoryGrid.setContentsMargins(11, 11, 11, 11)
        self.direcoryGrid.setSpacing(6)
        self.direcoryGrid.setObjectName("direcoryGrid")
        self.tvLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tvLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tvLabel.setObjectName("tvLabel")
        self.direcoryGrid.addWidget(self.tvLabel, 1, 0, 1, 1)
        self.moviesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.moviesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.moviesLabel.setObjectName("moviesLabel")
        self.direcoryGrid.addWidget(self.moviesLabel, 0, 0, 1, 1)
        self.downloadLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.downloadLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.downloadLabel.setObjectName("downloadLabel")
        self.direcoryGrid.addWidget(self.downloadLabel, 2, 0, 1, 1)
        self.moviesChoose = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.moviesChoose.setObjectName("moviesChoose")
        self.direcoryGrid.addWidget(self.moviesChoose, 0, 3, 1, 1)
        self.tvChoose = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.tvChoose.setObjectName("tvChoose")
        self.direcoryGrid.addWidget(self.tvChoose, 1, 3, 1, 1)
        self.tvEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tvEdit.setObjectName("tvEdit")
        self.direcoryGrid.addWidget(self.tvEdit, 1, 1, 1, 2)
        self.downloadEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.downloadEdit.setObjectName("downloadEdit")
        self.direcoryGrid.addWidget(self.downloadEdit, 2, 1, 1, 2)
        self.downloadChoose = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.downloadChoose.setObjectName("downloadChoose")
        self.direcoryGrid.addWidget(self.downloadChoose, 2, 3, 1, 1)
        self.moviesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.moviesEdit.setObjectName("moviesEdit")
        self.direcoryGrid.addWidget(self.moviesEdit, 0, 1, 1, 2)
        self.varsBox = QtWidgets.QGroupBox(self.centralWidget)
        self.varsBox.setGeometry(QtCore.QRect(10, 170, 531, 191))
        self.varsBox.setObjectName("varsBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.varsBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(60, 20, 425, 163))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.varsGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.varsGridLayout.setContentsMargins(11, 11, 11, 11)
        self.varsGridLayout.setSpacing(6)
        self.varsGridLayout.setObjectName("varsGridLayout")
        self.filebotChooser = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.filebotChooser.setObjectName("filebotChooser")
        self.varsGridLayout.addWidget(self.filebotChooser, 2, 4, 1, 1)
        self.binDirectory = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binDirectory.sizePolicy().hasHeightForWidth())
        self.binDirectory.setSizePolicy(sizePolicy)
        self.binDirectory.setObjectName("binDirectory")
        self.varsGridLayout.addWidget(self.binDirectory, 3, 1, 1, 3)
        self.prognameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.prognameEdit.setObjectName("prognameEdit")
        self.varsGridLayout.addWidget(self.prognameEdit, 0, 1, 1, 4)
        self.testmodeCheck = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.testmodeCheck.setObjectName("testmodeCheck")
        self.varsGridLayout.addWidget(self.testmodeCheck, 4, 1, 1, 1)
        self.filebotLocLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.filebotLocLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filebotLocLabel.setObjectName("filebotLocLabel")
        self.varsGridLayout.addWidget(self.filebotLocLabel, 2, 0, 1, 1)
        self.progdirLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.progdirLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progdirLabel.setObjectName("progdirLabel")
        self.varsGridLayout.addWidget(self.progdirLabel, 3, 0, 1, 1)
        self.versionLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.versionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.varsGridLayout.addWidget(self.versionLabel, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.varsGridLayout.addItem(spacerItem, 1, 2, 1, 2)
        self.filebotLocEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.filebotLocEdit.setObjectName("filebotLocEdit")
        self.varsGridLayout.addWidget(self.filebotLocEdit, 2, 1, 1, 3)
        self.progLocationChooser = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.progLocationChooser.setObjectName("progLocationChooser")
        self.varsGridLayout.addWidget(self.progLocationChooser, 3, 4, 1, 1)
        self.progNameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.progNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progNameLabel.setObjectName("progNameLabel")
        self.varsGridLayout.addWidget(self.progNameLabel, 0, 0, 1, 1)
        self.versionEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionEdit.sizePolicy().hasHeightForWidth())
        self.versionEdit.setSizePolicy(sizePolicy)
        self.versionEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.versionEdit.setBaseSize(QtCore.QSize(75, 0))
        self.versionEdit.setObjectName("versionEdit")
        self.varsGridLayout.addWidget(self.versionEdit, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 371, 481, 63))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 15, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setDefault(False)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        Configuration.setCentralWidget(self.centralWidget)

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        _translate = QtCore.QCoreApplication.translate
        Configuration.setWindowTitle(_translate("Configuration", "ConfigWindow"))
        self.mediaBox.setTitle(_translate("Configuration", "Media Directories"))
        self.tvLabel.setText(_translate("Configuration", "TV Shows"))
        self.moviesLabel.setText(_translate("Configuration", "Movies"))
        self.downloadLabel.setText(_translate("Configuration", "Downloads"))
        self.moviesChoose.setText(_translate("Configuration", "..."))
        self.tvChoose.setText(_translate("Configuration", "..."))
        self.downloadChoose.setText(_translate("Configuration", "..."))
        self.varsBox.setTitle(_translate("Configuration", "System Variables"))
        self.filebotChooser.setText(_translate("Configuration", "..."))
        self.testmodeCheck.setText(_translate("Configuration", "Test Mode"))
        self.filebotLocLabel.setText(_translate("Configuration", "Filebot Location"))
        self.progdirLabel.setText(_translate("Configuration", "Program Directory"))
        self.versionLabel.setText(_translate("Configuration", "Version Number"))
        self.progLocationChooser.setText(_translate("Configuration", "..."))
        self.progNameLabel.setText(_translate("Configuration", "Program Title"))
        self.cancelButton.setText(_translate("Configuration", "Cancel"))
        self.okButton.setText(_translate("Configuration", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Configuration = QtWidgets.QMainWindow()
    ui = Ui_Configuration()
    ui.setupUi(Configuration)
    Configuration.show()
    sys.exit(app.exec_())

